"""Run schema validation against planner/research/scene/script JSON outputs."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Dict, Iterable, Set

try:
    from .run_logger import build_metrics, emit_run_log
except Exception:  # pragma: no cover - allows local schema checks without Supabase env
    def build_metrics(*, latency_ms: int = 0, tokens: int = 0, cost_usd: float = 0.0, cache_hit: bool = False, retry_count: int = 0):
        return {
            "latency_ms": latency_ms,
            "tokens": tokens,
            "cost_usd": cost_usd,
            "cache_hit": cache_hit,
            "retry_count": retry_count,
        }

    def emit_run_log(**_kwargs):
        return "local-validation-no-runlog"

from .schema_validator import validate_json_file, validate_payload
from .storage_utils import normalize_video_id


VALIDATION_TARGETS = {
    "hook": "hook_output",
    "plan": "planner_output",
    "research": "research_output",
    "beat_graph": "beat_graph_output",
    "visual_beat_graph": "visual_beat_graph_output",
    "shorts_intelligence": "shorts_intelligence_output",
    "retention_events": "retention_feature_event_bundle",
    "learning_gate": "learning_gate_output",
    "scenes": "scene_bundle",
    "script": "script_output",
}

OPTIONAL_STAGES = {
    "hook",
    "beat_graph",
    "visual_beat_graph",
    "shorts_intelligence",
    "retention_events",
    "learning_gate",
}

CORE_STAGES = {
    "research",
    "plan",
    "script",
    "scenes",
}

TOGGLE_STAGE_MAP = {
    "HOOK_SHADOW_ENABLED": "hook",
    "BEAT_SHADOW_ENABLED": "beat_graph",
    "VISUAL_BEAT_SHADOW_ENABLED": "visual_beat_graph",
    "SHORTS_INTEL_SHADOW_ENABLED": "shorts_intelligence",
    "RETENTION_EVENTS_ENABLED": "retention_events",
}

PROFILE_DEFAULTS = {
    "core": {
        "HOOK_SHADOW_ENABLED": False,
        "BEAT_SHADOW_ENABLED": False,
        "VISUAL_BEAT_SHADOW_ENABLED": False,
        "SHORTS_INTEL_SHADOW_ENABLED": False,
        "RETENTION_EVENTS_ENABLED": False,
    },
    "shadow": {
        "HOOK_SHADOW_ENABLED": True,
        "BEAT_SHADOW_ENABLED": True,
        "VISUAL_BEAT_SHADOW_ENABLED": True,
        "SHORTS_INTEL_SHADOW_ENABLED": True,
        "RETENTION_EVENTS_ENABLED": False,
    },
    "full_shadow": {
        "HOOK_SHADOW_ENABLED": True,
        "BEAT_SHADOW_ENABLED": True,
        "VISUAL_BEAT_SHADOW_ENABLED": True,
        "SHORTS_INTEL_SHADOW_ENABLED": True,
        "RETENTION_EVENTS_ENABLED": True,
    },
}

STAGE_FILENAMES = {
    "hook": "{video_id}_hook.json",
    "research": "{video_id}_research.json",
    "plan": "{video_id}_plan.json",
    "beat_graph": "{video_id}_beat_graph.json",
    "visual_beat_graph": "{video_id}_visual_beat_graph.json",
    "scenes": "{video_id}_scenes.json",
    "shorts_intelligence": "{video_id}_shorts_intelligence.json",
    "retention_events": "{video_id}_retention_events.json",
    "learning_gate": "{video_id}_learning_gate.json",
    "script": "{video_id}_script.json",
}


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _load_manifest(video_id: str) -> Dict[str, object]:
    manifest_path = Path(__file__).resolve().parent.parent / "data" / f"{video_id}_pipeline.json"
    if not manifest_path.exists():
        return {}
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def _resolve_expected_stages(video_id: str) -> Set[str]:
    expected = set(CORE_STAGES)

    manifest = _load_manifest(video_id)
    manifest_toggles = manifest.get("shadow_toggles") if isinstance(manifest.get("shadow_toggles"), dict) else None

    if manifest_toggles:
        for toggle_name, stage in TOGGLE_STAGE_MAP.items():
            if bool(manifest_toggles.get(toggle_name)):
                expected.add(stage)
    else:
        profile = str(os.getenv("PIPELINE_PROFILE", "core")).strip().lower()
        defaults = PROFILE_DEFAULTS.get(profile, PROFILE_DEFAULTS["core"])
        for toggle_name, stage in TOGGLE_STAGE_MAP.items():
            if _env_bool(toggle_name, bool(defaults.get(toggle_name, False))):
                expected.add(stage)

    # learning gate is generated by analytics collector, not pipeline runner.
    return expected


def validate_files(stage: str, json_paths: Iterable[str]) -> None:
    schema_name = VALIDATION_TARGETS[stage]
    for path in json_paths:
        if stage == "scenes":
            payload = json.loads(Path(path).read_text(encoding="utf-8"))
            if isinstance(payload, dict) and "scenes" in payload:
                scenes = payload.get("scenes", [])
                if not scenes:
                    raise ValueError("Scene output missing 'scenes' array.")
                validate_payload(schema_name, payload)
                for scene in scenes:
                    validate_payload("scene_output", scene)
            else:
                validate_payload("scene_output", payload)
        elif stage == "retention_events":
            payload = json.loads(Path(path).read_text(encoding="utf-8"))
            validate_payload(schema_name, payload)
            for event in payload.get("events", []):
                validate_payload("retention_feature_event", event)
        else:
            validate_json_file(schema_name, path)


def validate_all(video_id: str) -> None:
    data_dir = Path(__file__).resolve().parent.parent / "data"
    expected = _resolve_expected_stages(video_id)
    for stage, template in STAGE_FILENAMES.items():
        path = data_dir / template.format(video_id=video_id)
        must_exist = stage in expected
        if not path.exists():
            if must_exist:
                raise FileNotFoundError(f"Missing file for stage {stage}: {path}")
            if stage in OPTIONAL_STAGES:
                continue
            continue
        validate_files(stage, [str(path)])


def main() -> int:
    if len(sys.argv) < 3:
        print(
            "Usage: python -m lib.validation_runner <hook|plan|research|beat_graph|visual_beat_graph|shorts_intelligence|retention_events|learning_gate|scenes|script|all> <json_path>...",
            file=sys.stderr,
        )
        return 1

    stage = sys.argv[1].strip().lower()
    if stage == "all":
        if len(sys.argv) < 4 or sys.argv[2] != "--url":
            print(
                "Usage: python -m lib.validation_runner all --url <youtube_url_or_id>",
                file=sys.stderr,
            )
            return 1
        video_id = normalize_video_id(sys.argv[3])
        json_paths = []
    elif stage not in VALIDATION_TARGETS:
        print(f"Unknown stage: {stage}", file=sys.stderr)
        return 1
    else:
        json_paths = [str(Path(path)) for path in sys.argv[2:]]

    try:
        if stage == "all":
            validate_all(video_id)
        else:
            validate_files(stage, json_paths)
        emit_run_log(
            stage="validation",
            status="success",
            input_refs={"stage": stage, "files": json_paths or ["data/*"]},
            metrics=build_metrics(cache_hit=False),
        )
        print("Validation passed.")
        return 0
    except Exception as exc:
        emit_run_log(
            stage="validation",
            status="failure",
            input_refs={"stage": stage, "files": json_paths},
            error_summary=str(exc),
            metrics=build_metrics(cache_hit=False),
        )
        print(f"Validation failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
