-- Stage execution ledger for deterministic retry/idempotency diagnostics.
-- Safe to re-run.

CREATE TABLE IF NOT EXISTS public.stage_execution_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id text NOT NULL,
  run_id text NOT NULL,
  stage text NOT NULL,
  attempt integer NOT NULL,
  status text NOT NULL,
  error_summary text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_stage_execution_ledger_identity
  ON public.stage_execution_ledger(video_id, run_id, stage, attempt);

CREATE INDEX IF NOT EXISTS idx_stage_execution_ledger_video_run
  ON public.stage_execution_ledger(video_id, run_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_stage_execution_ledger_stage_status
  ON public.stage_execution_ledger(stage, status, created_at DESC);

CREATE OR REPLACE FUNCTION public.touch_stage_execution_ledger_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_stage_execution_ledger_updated_at ON public.stage_execution_ledger;
CREATE TRIGGER trg_touch_stage_execution_ledger_updated_at
BEFORE UPDATE ON public.stage_execution_ledger
FOR EACH ROW
EXECUTE FUNCTION public.touch_stage_execution_ledger_updated_at();
