-- Shadow/Learning schema migration
-- Safe to re-run (idempotent where possible).

-- 1) Optional execution-tracking columns on video_uploads
ALTER TABLE IF EXISTS public.video_uploads
  ADD COLUMN IF NOT EXISTS pipeline_profile text,
  ADD COLUMN IF NOT EXISTS selected_hook_stage text,
  ADD COLUMN IF NOT EXISTS shadow_toggles jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS hook_seed_path text,
  ADD COLUMN IF NOT EXISTS hook_refined_path text;

-- 2) Retention events table (append-only)
CREATE TABLE IF NOT EXISTS public.retention_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id text NOT NULL,
  event_type text NOT NULL,
  event_window text,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_retention_events_video_id_created_at
  ON public.retention_events(video_id, created_at DESC);

-- 3) Learning gate decisions table (latest decision upsert by video_id)
CREATE TABLE IF NOT EXISTS public.learning_gates (
  video_id text PRIMARY KEY,
  decision text,
  action text,
  policy text,
  window_size integer,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Keep updated_at current on upsert/update.
CREATE OR REPLACE FUNCTION public.touch_learning_gates_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_learning_gates_updated_at ON public.learning_gates;
CREATE TRIGGER trg_touch_learning_gates_updated_at
BEFORE UPDATE ON public.learning_gates
FOR EACH ROW
EXECUTE FUNCTION public.touch_learning_gates_updated_at();
