-- Shadow/Learning schema migration
-- Safe to re-run (idempotent where possible).

-- 1) Optional execution-tracking columns on video_uploads
ALTER TABLE IF EXISTS public.video_uploads
  ADD COLUMN IF NOT EXISTS pipeline_profile text,
  ADD COLUMN IF NOT EXISTS selected_hook_stage text,
  ADD COLUMN IF NOT EXISTS shadow_toggles jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS hook_seed_path text,
  ADD COLUMN IF NOT EXISTS hook_refined_path text;

-- 2) Retention events table (append-only, lineage-aware)
CREATE TABLE IF NOT EXISTS public.retention_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id text NOT NULL,
  run_id text,
  artifact_type text,
  artifact_version text,
  event_type text NOT NULL,
  event_window text,
  scoring_model_version text,
  prompt_hash text,
  scene_contract_version text,
  event_key text,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS public.retention_events
  ADD COLUMN IF NOT EXISTS run_id text,
  ADD COLUMN IF NOT EXISTS artifact_type text,
  ADD COLUMN IF NOT EXISTS artifact_version text,
  ADD COLUMN IF NOT EXISTS scoring_model_version text,
  ADD COLUMN IF NOT EXISTS prompt_hash text,
  ADD COLUMN IF NOT EXISTS scene_contract_version text,
  ADD COLUMN IF NOT EXISTS event_key text;

CREATE INDEX IF NOT EXISTS idx_retention_events_video_id_created_at
  ON public.retention_events(video_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_retention_events_join_key
  ON public.retention_events(video_id, run_id, artifact_type, artifact_version, event_type, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_retention_events_event_key
  ON public.retention_events(event_key)
  WHERE event_key IS NOT NULL;

-- 3) Learning gate latest decisions (upsert by video_id)
CREATE TABLE IF NOT EXISTS public.learning_gates (
  video_id text PRIMARY KEY,
  decision text,
  action text,
  policy jsonb,
  window_size integer,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS public.learning_gates
  ADD COLUMN IF NOT EXISTS policy jsonb,
  ADD COLUMN IF NOT EXISTS window_size integer;

-- Keep updated_at current on upsert/update.
CREATE OR REPLACE FUNCTION public.touch_learning_gates_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_learning_gates_updated_at ON public.learning_gates;
CREATE TRIGGER trg_touch_learning_gates_updated_at
BEFORE UPDATE ON public.learning_gates
FOR EACH ROW
EXECUTE FUNCTION public.touch_learning_gates_updated_at();

-- 4) Learning gate decision history (append-only for experiments)
CREATE TABLE IF NOT EXISTS public.learning_gate_decisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id text NOT NULL,
  run_id text,
  artifact_type text,
  artifact_version text,
  decision text,
  action text,
  policy jsonb,
  window_size integer,
  evaluated_outcomes integer,
  decision_key text,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS public.learning_gate_decisions
  ADD COLUMN IF NOT EXISTS decision_key text;

CREATE INDEX IF NOT EXISTS idx_learning_gate_decisions_video_created_at
  ON public.learning_gate_decisions(video_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_learning_gate_decisions_join_key
  ON public.learning_gate_decisions(video_id, run_id, artifact_type, artifact_version, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_learning_gate_decisions_decision_key
  ON public.learning_gate_decisions(decision_key)
  WHERE decision_key IS NOT NULL;
